// Mocks generated by Mockito 5.4.6 from annotations
// in finbuddy/test/viewmodels/cartoes/cartoes_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:finbuddy/shared/core/models/cartao_model.dart' as _i4;
import 'package:finbuddy/shared/core/repositories/cartoes_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CartoesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartoesRepository extends _i1.Mock implements _i2.CartoesRepository {
  MockCartoesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.CartaoModel>> getCartoesStream() =>
      (super.noSuchMethod(
            Invocation.method(#getCartoesStream, []),
            returnValue: _i3.Stream<List<_i4.CartaoModel>>.empty(),
          )
          as _i3.Stream<List<_i4.CartaoModel>>);

  @override
  _i3.Future<void> addOrEditCartao(_i4.CartaoModel? cartao) =>
      (super.noSuchMethod(
            Invocation.method(#addOrEditCartao, [cartao]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCartao(String? cartaoId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCartao, [cartaoId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.CartaoModel>> getCartoes() =>
      (super.noSuchMethod(
            Invocation.method(#getCartoes, []),
            returnValue: _i3.Future<List<_i4.CartaoModel>>.value(
              <_i4.CartaoModel>[],
            ),
          )
          as _i3.Future<List<_i4.CartaoModel>>);
}
