// Mocks generated by Mockito 5.4.6 from annotations
// in finbuddy/test/viewmodels/aportes/aportes_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:finbuddy/shared/core/models/aporte_meta_model.dart' as _i4;
import 'package:finbuddy/shared/core/repositories/aportes_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AportesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAportesRepository extends _i1.Mock implements _i2.AportesRepository {
  MockAportesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.AporteMetaModel>> getAportesStream(String? metaId) =>
      (super.noSuchMethod(
            Invocation.method(#getAportesStream, [metaId]),
            returnValue: _i3.Stream<List<_i4.AporteMetaModel>>.empty(),
          )
          as _i3.Stream<List<_i4.AporteMetaModel>>);

  @override
  _i3.Future<void> recalcularEAtualizarValorMeta(String? metaId) =>
      (super.noSuchMethod(
            Invocation.method(#recalcularEAtualizarValorMeta, [metaId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addOrEditAporte(
    String? metaId,
    _i4.AporteMetaModel? aporte,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addOrEditAporte, [metaId, aporte]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAporte(String? metaId, String? aporteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAporte, [metaId, aporteId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
